trigger:
  batch: true
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - LICENSE
      - README.md

pool:
  vmImage: vs2017-win2016

variables:
  configuration: Release

steps:
  - task: GitVersion@4
    displayName: Set version
    inputs:
      updateAssemblyInfo: true

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: 'src/**/*.csproj'
      configuration: $(configuration)
  
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: 'src/**/*Test*.csproj'
      configuration: $(configuration)
      nobuild: true
      arguments: /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Include="[$(System.TeamProject)*]*" /p:Exclude="[*Test*]*"

  - script: |
      dotnet tool install -g dotnet-reportgenerator-globaltool
      reportgenerator -reports:$(Build.SourcesDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:"Cobertura"
    displayName: Generate code coverage report

  - task: PublishCodeCoverageResults@1
    displayName: Publish code coverage results
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'

  - task: Npm@1
    displayName: Set up documentation CLI
    inputs:
      command: custom
      customCommand: install --only=prod
      workingDir: docs

  - task: Npm@1
    displayName: Build documentation
    inputs:
      command: custom
      customCommand: run build
      workingDir: docs

  - task: PublishBuildArtifacts@1
    displayName: Publish documentation artifact
    inputs:
      pathToPublish: docs/_site
      ArtifactName: docs

  - task: DotNetCoreCLI@2
    displayName: Pack NuGet packages
    inputs:
      command: pack
      packDirectory: '$(Build.ArtifactStagingDirectory)'
      configuration: $(configuration)
      nobuild: true
      workingDirectory: src
 
  - task: PublishBuildArtifacts@1
    displayName: Publish NuGet packages artifact
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: nupkgs

  - task: GitHubPagesPublish@1
    inputs:
      docPath: docs/_site
      githubUsername: softframe
      githubEmail: mgelinas@softframe.net
      githubAccessToken: 7c44a82d944cdef3d4e7752b2594cc4f1f65a5d0
      repositoryName: railsharp
      branchName: gh-pages
      commitMessage: 'Automated Build $(Build.BuildNumber)'