trigger:
  batch: true
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - LICENSE
      - README.md

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  versionPrefix: '0.2'
  versionPrerelease: 'unstable'
  configuration: 'Release'

name: $(versionPrefix)$(Rev:.r)

steps:
  - powershell: |
      $prefix = $Env:VERSIONPREFIX
      $prerelease = if ($Env:BUILD_SOURCEBRANCHNAME -eq 'master') {''} else {"-$Env:VERSIONPRERELEASE"}
      $revision = $Env:BUILD_BUILDNUMBER.Substring($Env:BUILD_BUILDNUMBER.LastIndexOf('.'))
      $version = "$prefix$prerelease$revision"
      Write-Host "Setting build number to: $version..."
      Write-Host "##vso[build.updatebuildnumber]$version"
    displayName: Set build number

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.csproj'
      configuration: $(configuration)
  
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: 'test/**/*.csproj'
      configuration: $(configuration)
      nobuild: true

  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
      packDirectory: '$(Build.ArtifactStagingDirectory)'
      workingDirectory: '$(Join-Path -Path Build.SourcesDirectory -ChildPath "src")'
      configuration: $(configuration)
      nobuild: true
 
  - task: PublishBuildArtifacts@1
    displayName: Publish build artifacts
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'