# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - LICENSE
      - README.md

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  version: '0.1.0'
  projectUrl: 'https://github.com/softframe/railsharp'
  licenseUrl: 'https://github.com/softframe/railsharp/blob/master/LICENSE'
  iconUrl: 'https://i.imgur.com/NvKVr6B.png'
  copyright: 'Copyright (c) 2019 SoftFrame'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: pack
    packagesToPack: '**/*.nuspec'
    nobuild: true
    buildProperties: 'version=$(version);authors=$(system.teamProject) Team;title=$(system.teamProject);projectUrl=$(projectUrl);licenseUrl=$(licenseUrl);iconUrl=$(iconUrl);requireLicenseAcceptance=false;copyright=$(copyright);configuration=$(buildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy build output to artifact staging directory'
  inputs:
    sourceFolder: '$(build.sourcesDirectory)'
    contents: '**/bin/$(buildConfiguration)/**'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)'

