trigger:
  batch: true
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - LICENSE
      - README.md

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  configuration: 'Release'
  prerelease: ci

steps:
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
  
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      projects: 'test/**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: dotnet pack
    inputs:
      command: pack
      packDirectory: '$(build.artifactStagingDirectory)/packages'
 
  - task: PublishBuildArtifacts@1
    displayName: publish artifacts
    #condition: $(and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
    inputs:
      PathtoPublish: '$(build.artifactStagingDirectory)'

  - task: DotNetCoreCLI@2
    displayName: dotnet nuget push
    #condition: $(and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
    inputs:
      command: custom
      custom: nuget
      arguments: push $(build.artifactStagingDirectory)/packages/*.nupkg --source https://api.nuget.org/v3/index.json --no-service-endpoint --api-key $(nuget.apiKey)
