trigger:
  batch: true
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - LICENSE
      - README.md

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: cd src && dotnet build -c $(buildConfiguration)
  displayName: 'Build'

- script: cd src && dotnet test -c $(buildConfiguration) --collect "Code coverage" -l trx --no-build
  displayName: 'Test'

- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: cd src && dotnet pack -c $(buildConfiguration) --include-source --include-symbols --no-build -o "$(build.artifactStagingDirectory)"
  displayName: 'Pack'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
